### ISSUE TITLE
Allow different style for placeholder

### ISSUE THREAD

**Issue by alexDevBR** [giorgosart/react-easy-edit#138]
What the title says. For example if displaying a table where a value is present for some rows, and not for others this will allow the user to easily notice what still needs to be filled in.

The solution could be as simple as adding a class to the div while the placeholder is being displayed.

I found a simple workaround for this:

```html
<EasyEdit
      viewAttributes={ hasValue ? {} : { className: "no-value" } }
```
and the style can be defined like this:
```css
div.easy-edit-wrapper.no-value  {
  color: darkgray;
}
```
